name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    # Run daily at 2am UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev-lock.txt
          pip install bandit[toml] safety

      - name: Run Bandit security scan
        run: |
          bandit -r agentsystems_sdk -f json -o bandit-report.json
          echo "## Bandit Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat bandit-report.json | python -m json.tool | head -50 >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Check for high severity issues
          if python -c "import json; data=json.load(open('bandit-report.json')); exit(0 if len([i for i in data['results'] if i['issue_severity'] == 'HIGH']) == 0 else 1)"; then
            echo "✅ No high severity issues found" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ High severity issues detected!" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Check dependency vulnerabilities with Safety
        run: |
          echo "## Safety Dependency Scan" >> $GITHUB_STEP_SUMMARY

          # Run safety check and capture output
          if safety check --json > safety-report.json 2>&1; then
            echo "✅ No known vulnerabilities found in dependencies" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Vulnerabilities found in dependencies:" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat safety-report.json | python -m json.tool | head -50 >> $GITHUB_STEP_SUMMARY || true
            echo '```' >> $GITHUB_STEP_SUMMARY

            # Don't fail the build for known vulnerabilities, just warn
            echo "::warning::Dependency vulnerabilities detected. Please review the Safety report."
          fi

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            bandit-report.json
            safety-report.json

      - name: SAST with CodeQL (if enabled)
        uses: github/codeql-action/analyze@v2
        if: github.repository == 'agentsystems/agentsystems-sdk'
        continue-on-error: true
